from easytour.prompts.upload.import_prompt import (
    ITEM_NAME_SYSTEM_PROMPT,
    ITEM_NAME_USER_PROMPT_TEMPLATE,
    DOC_LEVEL_EXTRACT_SYSTEM,
    DOC_LEVEL_EXTRACT_USER_TEMPLATE,
    CHUNK_LEVEL_EXTRACT_SYSTEM,
    CHUNK_LEVEL_EXTRACT_COMMON_FIELDS,
    CHUNK_LEVEL_EXTRA_FIELDS,
    CHUNK_LEVEL_EXTRACT_USER_TEMPLATE,
)

__all__ = [
    'ITEM_NAME_SYSTEM_PROMPT',
    'ITEM_NAME_USER_PROMPT_TEMPLATE',
    'DOC_LEVEL_EXTRACT_SYSTEM',
    'DOC_LEVEL_EXTRACT_USER_TEMPLATE',
    'CHUNK_LEVEL_EXTRACT_SYSTEM',
    'CHUNK_LEVEL_EXTRACT_COMMON_FIELDS',
    'CHUNK_LEVEL_EXTRA_FIELDS',
    'CHUNK_LEVEL_EXTRACT_USER_TEMPLATE',
]
